# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16x3LTB-0M9ofWRrRyuWiyrvKwbCaziB5
"""

import torch
import torch.nn as nn

class Encoder(nn.Module):
  def __init__(self, input_dim = 12, latent_dim = 64):
    super(Encoder, self).__init__()
    self.fc1 = nn.Linear(input_dim, 64)
    self.fc2 = nn.Linear(64, 32)
    self.fc3 = nn.Linear(32, latent_dim) #maybe latent space should be way smaller to actually give compression
    self.relu = nn.ReLU()

  def forward(self, x):
    x = self.relu(self.fc1(x))
    x = self.relu(self.fc2(x))
    x =self.fc3(x)
    return x

class Decoder(nn.Module):
  def __init__(self, latent_dim = 32, output_dim =12):
   super(Decoder, self).__init__()
   self.fc1 = nn.Linear(latent_dim, 32)
   self.fc2 = nn.Linear(32, 64)
   self.fc3 = nn.Linear(64, output_dim)
   self.relu = nn.ReLU()

  def forward(self, x):
    x = self.relu(self.fc1(x))
    x = self.relu(self.fc2(x))
    x = self.fc3(x)
    return x

class Autoencoder(nn.Module):
  def __init__(self, input_dim = 12, latent_dim = 32):
    super(Autoencoder, self).__init__()
    self.encoder = Encoder(input_dim=input_dim, latent_dim = latent_dim)
    self.decoder = Decoder(latent_dim = latent_dim, output_dim = input_dim)

  def forward(self, x):
    encoded = self.encoder(x)
    decoded = self.decoder(encoded)
    return decoded

